services:
  api:
    build: .
    image: antifraud-api:dev
    container_name: antifraud-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MOBILE_MODEL_PATH: /models/mobile_best.pt
      WEB_MODEL_PATH: /models/web_best.pt
      CUSTOMER_HISTORY_PATH: /models/customer_features.parquet
      OLLAMA_URL: http://host.docker.internal:11434
      MERCHANT_API_URL: http://merchant_mock:9000
    volumes:
      - ./models:/models:ro
      - ./app:/app/app:ro
      - ./tests:/app/tests:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - merchant_mock

  merchant_mock:
    build: ./merchant_mock
    image: antifraud-merchant-mock:dev
    container_name: antifraud-merchant-mock
    ports:
      - "9000:9000"
